version: 3

tasks:
  minigrep-cli-tests:
    desc: "Save excessive wear-and-tear on the up arrow!"
    dir: /vagrant/git/minigrep
    cmds:
      - cmd: cargo run
        ignore_error: true
      - cmd: cargo run -- body sample-poem-not-there.txt
        ignore_error: true
      - cargo run -- body sample-poem.txt
    silent: true
    

